//! # Indicator Registry — Single Source of Truth
//!
//! Every indicator in the system is declared exactly once here. The backend
//! (normalization, persistence, scoring) and the frontend (telemetry
//! matrix, chart toggles, scoring UI) all derive their behavior from this
//! manifest, which is serialized to the frontend via `/api/config`.
//!
//! Adding an indicator = one entry here + its calculator + its normalize mapper
//! + (its chart component). No scattered hardcoded lists.

use super::normalized::SignalKind;
use serde::Serialize;

/// Functional category (blueprint grouping).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
pub enum IndicatorGroup {
    Trend,
    Momentum,
    Volume,
    Volatility,
    Structure,
    Regime,
    Institutional,
    DerivativesData,
}

/// Predictive class (leading vs confirming).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum IndicatorClass {
    Leading,
    Hybrid,
    Lagging,
}

/// Where the indicator renders in the frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum RenderKind {
    /// Its own oscillator/volume pane chart.
    Pane,
    /// A line/series drawn on the main price chart.
    PriceOverlay,
    /// Horizontal price-level lines on the main price chart.
    PriceLevels,
    /// Event markers only (no dedicated series).
    Marker,
}

/// Static metadata describing one indicator end-to-end.
#[derive(Debug, Clone, Serialize)]
pub struct IndicatorMeta {
    pub key: &'static str,
    pub display_name: &'static str,
    pub group: IndicatorGroup,
    pub class: IndicatorClass,
    pub render: RenderKind,
    /// `true` = signed [-1,1] scoring contributor; `false` = non-directional gate/multiplier.
    pub directional: bool,
    pub supports_divergence: bool,
    pub signal_types: &'static [SignalKind],
    pub default_weight: f64,
    pub default_enabled: bool,
    pub config_params: &'static [&'static str],
    /// Frontend raw-cell render hint: "decimals1|decimals2|decimals4|percent1|price|ratio2|onoff".
    pub value_format: &'static str,
    /// Where the raw cell reads from: "raw" | "sub:<key>" | "state".
    pub value_source: &'static str,
    /// Primary chart color (hex).
    pub color: &'static str,
    /// Documentation section id in docs/indicators-guide.md.
    pub guide_section: &'static str,
    /// Minimum number of input bars the calculator needs before it can emit
    /// a non-`None` reading. Drives the per-indicator `Loading → Live`
    /// transition in [03-02-15 ILS-11](../docs/engines/market-monitoring-engine/03-02-15-mme-indicator-lifecycle-states.md).
    /// For 50 indicators at the canonical `[candle_buffer] size = 500`,
    /// every `bars_required ≤ 200` so a fully-warmed pipeline is `Live`
    /// across all indicators (DCP-04 / ILS-05).
    pub bars_required: u32,
}

use IndicatorClass::*;
use IndicatorGroup::*;
use RenderKind::*;
use SignalKind::*;

/// The authoritative indicator manifest (Ichimoku + Pivot Points are the
/// deferred Institutional tier and intentionally omitted from the current build).
pub const INDICATORS: &[IndicatorMeta] = &[
    // ─────────── TREND ───────────
    IndicatorMeta {
        key: "ema_stack",
        display_name: "EMA Ribbon",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[StackChange, Crossover],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["ema_fast", "ema_medium", "ema_slow", "ema_long"],
        value_format: "price",
        value_source: "sub:fast",
        color: "#fdd835",
        guide_section: "6",
        bars_required: 200,
    },
    IndicatorMeta {
        key: "supertrend",
        display_name: "Supertrend",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[TrendFlip, Crossover, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["supertrend_period", "supertrend_multiplier"],
        value_format: "price",
        value_source: "sub:line",
        color: "#26a69a",
        guide_section: "14",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "donchian",
        display_name: "Donchian",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, BandTouch, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["donchian_period"],
        value_format: "price",
        value_source: "sub:upper",
        color: "#ec407a",
        guide_section: "16",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "keltner",
        display_name: "Keltner",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, BandTouch, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[
            "keltner_ema_period",
            "keltner_atr_period",
            "keltner_multiplier",
        ],
        value_format: "price",
        value_source: "sub:middle",
        color: "#78909c",
        guide_section: "15",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "adx",
        display_name: "ADX",
        group: Trend,
        class: Lagging,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[TrendFlip, Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["adx_period"],
        value_format: "decimals2",
        value_source: "sub:adx",
        color: "#ff9800",
        guide_section: "4",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "vwap",
        display_name: "VWAP",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "price",
        value_source: "sub:vwap",
        color: "#2962ff",
        guide_section: "7",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "anchored_vwap",
        display_name: "Anchored VWAP",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Crossover, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "price",
        value_source: "sub:vwap_weekly",
        color: "#ffab40",
        guide_section: "34",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "ichimoku",
        display_name: "Ichimoku Cloud",
        group: Trend,
        class: Hybrid,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Crossover, Breakout, TrendFlip, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[
            "ichimoku_tenkan",
            "ichimoku_kijun",
            "ichimoku_senkou_b",
            "ichimoku_displacement",
        ],
        value_format: "price",
        value_source: "sub:tenkan",
        color: "#7e57c2",
        guide_section: "25",
        bars_required: 52,
    },
    // ─────────── MOMENTUM ───────────
    IndicatorMeta {
        key: "rsi",
        display_name: "RSI",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[Divergence, Threshold, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["rsi_period"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#7e57c2",
        guide_section: "1",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "stochastic",
        display_name: "Stochastic",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[Crossover, Threshold, Divergence, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["stoch_k_period", "stoch_d_period", "stoch_s_period"],
        value_format: "percent1",
        value_source: "sub:k_line",
        color: "#2962ff",
        guide_section: "12",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "chandemo",
        display_name: "Chande MO",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[ZeroLineCross, Threshold, Divergence],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["chandemo_period"],
        value_format: "decimals1",
        value_source: "raw",
        color: "#e040fb",
        guide_section: "13",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "williams_r",
        display_name: "Williams %R",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["williams_r_period"],
        value_format: "decimals1",
        value_source: "raw",
        color: "#81c784",
        guide_section: "28",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "hull_ma",
        display_name: "Hull MA",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Crossover],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["hull_ma_period"],
        value_format: "price",
        value_source: "raw",
        color: "#ff8a65",
        guide_section: "29",
        bars_required: 200,
    },
    IndicatorMeta {
        key: "awesome_oscillator",
        display_name: "AO",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[ZeroLineCross, Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "decimals4",
        value_source: "raw",
        color: "#4dd0e1",
        guide_section: "30",
        bars_required: 34,
    },
    IndicatorMeta {
        key: "force_index",
        display_name: "Force Idx",
        group: Volume,
        class: Hybrid,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[ZeroLineCross, Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["force_index_smoothing"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ce93d8",
        guide_section: "31",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "stddev_channel",
        display_name: "StdDev Chnl",
        group: Volatility,
        class: Hybrid,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, BandTouch, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["stddev_channel_period"],
        value_format: "price",
        value_source: "sub:center",
        color: "#a1887f",
        guide_section: "32",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "cci",
        display_name: "CCI",
        group: Momentum,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["cci_period"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ffb74d",
        guide_section: "26",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "macd",
        display_name: "MACD",
        group: Momentum,
        class: Lagging,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[Crossover, ZeroLineCross, Divergence, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["macd_fast", "macd_slow", "macd_signal"],
        value_format: "decimals4",
        value_source: "raw",
        color: "#26a69a",
        guide_section: "2",
        bars_required: 26,
    },
    // ─────────── VOLUME ───────────
    IndicatorMeta {
        key: "volume",
        display_name: "Volume",
        group: Volume,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[VolumeClimax],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["volume_average_period"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#26a69a",
        guide_section: "6",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "rvol",
        display_name: "RVOL",
        group: Volume,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[VolumeClimax],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["rvol_threshold_institutional", "rvol_threshold_climax"],
        value_format: "ratio2",
        value_source: "raw",
        color: "#ffa726",
        guide_section: "6",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "volume_profile",
        display_name: "Volume Profile",
        group: Volume,
        class: Hybrid,
        render: PriceLevels,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, LevelTest, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[
            "volume_profile_bins",
            "volume_profile_window",
            "volume_profile_value_area",
        ],
        value_format: "price",
        value_source: "sub:poc",
        color: "#bcaaa4",
        guide_section: "33",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "obv",
        display_name: "OBV",
        group: Volume,
        class: Lagging,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[Divergence, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["obv_smoothing"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#29b6f6",
        guide_section: "17",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "cmf",
        display_name: "Chaikin MF",
        group: Volume,
        class: Hybrid,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[ZeroLineCross, Divergence],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["cmf_period"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#26c6da",
        guide_section: "18",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "mfi",
        display_name: "Money Flow Idx",
        group: Volume,
        class: Hybrid,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[Threshold, Divergence, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["mfi_period"],
        value_format: "decimals1",
        value_source: "raw",
        color: "#ab47bc",
        guide_section: "19",
        bars_required: 20,
    },
    // ─────────── VOLATILITY ───────────
    IndicatorMeta {
        key: "atr",
        display_name: "ATR",
        group: Volatility,
        class: Lagging,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold, CompressionRelease],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["atr_period"],
        value_format: "price",
        value_source: "raw",
        color: "#ef5350",
        guide_section: "5",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "bollinger",
        display_name: "Bollinger",
        group: Volatility,
        class: Hybrid,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, BandTouch, LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "price",
        value_source: "sub:middle",
        color: "#00e5ff",
        guide_section: "5",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "bbwp",
        display_name: "BBWP",
        group: Volatility,
        class: Leading,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[CompressionRelease],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["bbwp_period", "bbwp_lookback"],
        value_format: "percent1",
        value_source: "raw",
        color: "#ffca28",
        guide_section: "9",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "squeeze",
        display_name: "TTM Squeeze",
        group: Volatility,
        class: Hybrid,
        render: Pane,
        directional: true,
        supports_divergence: true,
        signal_types: &[CompressionRelease, Divergence],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["squeeze_period"],
        value_format: "onoff",
        value_source: "state",
        color: "#b2ff59",
        guide_section: "3",
        bars_required: 20,
    },
    IndicatorMeta {
        key: "hv",
        display_name: "Hist. Volatility",
        group: Volatility,
        class: Lagging,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["hv_period"],
        value_format: "percent1",
        value_source: "raw",
        color: "#ff7043",
        guide_section: "20",
        bars_required: 20,
    },
    // ─────────── MARKET STRUCTURE ───────────
    IndicatorMeta {
        key: "fibonacci",
        display_name: "Fibonacci",
        group: Structure,
        class: Leading,
        render: PriceLevels,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "price",
        value_source: "sub:gp_top",
        color: "#ffd54f",
        guide_section: "8",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "support_resistance",
        display_name: "Support/Resistance",
        group: Structure,
        class: Leading,
        render: PriceLevels,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest, Breakout],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "price",
        value_source: "raw",
        color: "#90a4ae",
        guide_section: "8",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "pivot_points",
        display_name: "Pivot Points",
        group: Structure,
        class: Leading,
        render: PriceLevels,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest, Breakout, Crossover],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["pivot_points_method"],
        value_format: "price",
        value_source: "sub:pivot",
        color: "#8d6e63",
        guide_section: "8",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "psar",
        display_name: "Parabolic SAR",
        group: Trend,
        class: Lagging,
        render: PriceOverlay,
        directional: true,
        supports_divergence: false,
        signal_types: &[TrendFlip, Crossover],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["psar_af_step", "psar_af_max"],
        value_format: "price",
        value_source: "sub:sar",
        color: "#ffab40",
        guide_section: "27",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "patterns",
        display_name: "Patterns",
        group: Structure,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[PatternForming],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "percent1",
        value_source: "raw",
        color: "#ba68c8",
        guide_section: "10",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "candlestick",
        display_name: "Candlestick",
        group: Structure,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[PatternForming],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["candlestick_min_confidence"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#4db6ac",
        guide_section: "10",
        bars_required: 50,
    },
    // ─────────── MARKET REGIME ───────────
    IndicatorMeta {
        key: "aroon",
        display_name: "Aroon",
        group: Regime,
        class: Hybrid,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Crossover, Threshold, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["aroon_period"],
        value_format: "decimals1",
        value_source: "raw",
        color: "#26a69a",
        guide_section: "21",
        bars_required: 25,
    },
    IndicatorMeta {
        key: "choppiness",
        display_name: "Choppiness",
        group: Regime,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold, CompressionRelease],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["chop_period"],
        value_format: "decimals1",
        value_source: "raw",
        color: "#ffa726",
        guide_section: "22",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "linreg_slope",
        display_name: "LinReg Slope",
        group: Regime,
        class: Lagging,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["linreg_period"],
        value_format: "decimals4",
        value_source: "raw",
        color: "#42a5f5",
        guide_section: "23",
        bars_required: 14,
    },
    IndicatorMeta {
        key: "zscore",
        display_name: "Z-Score",
        group: Regime,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["zscore_period"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ec407a",
        guide_section: "24",
        bars_required: 14,
    },
    // ─────────── ADVANCED ───────────
    IndicatorMeta {
        key: "smc_structure",
        display_name: "SMC Structure",
        group: Institutional,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[Breakout, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["smc_lookback"],
        value_format: "decimals2",
        value_source: "sub:structure",
        color: "#ffab40",
        guide_section: "34",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "smc_liquidity",
        display_name: "SMC Liquidity",
        group: Institutional,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold, PatternForming],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["smc_lookback"],
        value_format: "decimals2",
        value_source: "sub:sweep_buy",
        color: "#ff7043",
        guide_section: "34",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "smc_fvg",
        display_name: "SMC Fair Value Gap",
        group: Institutional,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["smc_lookback"],
        value_format: "decimals2",
        value_source: "sub:fvg_top",
        color: "#ffca28",
        guide_section: "34",
        bars_required: 50,
    },
    IndicatorMeta {
        key: "smc_order_blocks",
        display_name: "SMC Order Blocks",
        group: Institutional,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[LevelTest, TrendFlip],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["smc_lookback"],
        value_format: "decimals2",
        value_source: "sub:ob_bullish_high",
        color: "#8d6e63",
        guide_section: "34",
        bars_required: 50,
    },
    // ─────────── DERIVATIVES DATA (Phase 11) ───────────
    IndicatorMeta {
        key: "open_interest",
        display_name: "Open Interest",
        group: DerivativesData,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["oi_lookback"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ffab40",
        guide_section: "35",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "oi_delta",
        display_name: "OI Delta",
        group: DerivativesData,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold, ZeroLineCross],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["oi_delta_window"],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ff6e40",
        guide_section: "35",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "funding_rate",
        display_name: "Funding Rate",
        group: DerivativesData,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &["funding_extreme_threshold"],
        value_format: "percent1",
        value_source: "raw",
        color: "#00e676",
        guide_section: "36",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "oi_price_divergence",
        display_name: "OI-Price Divergence",
        group: DerivativesData,
        class: Leading,
        render: Marker,
        directional: true,
        supports_divergence: false,
        signal_types: &[Divergence],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ff5252",
        guide_section: "35",
        bars_required: 1,
    },
    // ─────────── ORDER BOOK DEPTH (Phase 2) ───────────
    IndicatorMeta {
        key: "order_flow_imbalance",
        display_name: "Order Flow Imbalance",
        group: DerivativesData,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "decimals2",
        value_source: "raw",
        color: "#ff6d00",
        guide_section: "37",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "spread",
        display_name: "Spread",
        group: DerivativesData,
        class: Hybrid,
        render: Pane,
        directional: false,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "percent1",
        value_source: "raw",
        color: "#f48fb1",
        guide_section: "37",
        bars_required: 1,
    },
    IndicatorMeta {
        key: "depth_bias",
        display_name: "Depth Bias",
        group: DerivativesData,
        class: Leading,
        render: Pane,
        directional: true,
        supports_divergence: false,
        signal_types: &[Threshold],
        default_weight: 1.0,
        default_enabled: true,
        config_params: &[],
        value_format: "decimals2",
        value_source: "raw",
        color: "#18ffff",
        guide_section: "37",
        bars_required: 1,
    },
];

/// Return the full manifest as an owned vector (for API serialization).
pub fn all() -> Vec<IndicatorMeta> {
    INDICATORS.to_vec()
}

/// Look up an indicator's metadata by key.
pub fn get(key: &str) -> Option<&'static IndicatorMeta> {
    INDICATORS.iter().find(|m| m.key == key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_keys_unique() {
        let mut seen = std::collections::HashSet::new();
        for m in INDICATORS {
            assert!(seen.insert(m.key), "duplicate registry key: {}", m.key);
        }
    }

    #[test]
    fn test_registry_serializes() {
        let json = serde_json::to_string(&all()).expect("registry serializes");
        assert!(json.contains("supertrend"));
        assert!(json.contains("choppiness"));
    }

    #[test]
    fn test_directional_and_gate_counts() {
        let gates = INDICATORS.iter().filter(|m| !m.directional).count();
        // atr, bbwp, hv, volume, rvol, choppiness, funding_rate, spread, open_interest
        assert_eq!(gates, 9, "expected 9 non-directional gate indicators");
    }

    #[test]
    fn test_all_weights_are_one() {
        for m in INDICATORS {
            assert!(
                (m.default_weight - 1.0).abs() < 1e-9,
                "indicator '{}' has non-1.0 weight: {}",
                m.key,
                m.default_weight
            );
        }
    }
}
